// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0bXYe9u2EA6GprA1F1Qyd5UXgS5ukdsI',
    appId: '1:149157354469:android:a038a0e27b80a64a5a2d0c',
    messagingSenderId: '149157354469',
    projectId: 'portal-service-test',
    storageBucket: 'portal-service-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlKwRndu7gVNrI3Xxpf5h3z2FllXgjiJo',
    appId: '1:149157354469:ios:73b9f9b485e886165a2d0c',
    messagingSenderId: '149157354469',
    projectId: 'portal-service-test',
    storageBucket: 'portal-service-test.firebasestorage.app',
    iosBundleId: 'com.example.portalServiceTest',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlKwRndu7gVNrI3Xxpf5h3z2FllXgjiJo',
    appId: '1:149157354469:web:73b9f9b485e886165a2d0c',
    messagingSenderId: '149157354469',
    projectId: 'portal-service-test',
    storageBucket: 'portal-service-test.firebasestorage.app',
  );

}